- name: Install nginx webserver
  apt: name=nginx state=latest update_cache=yes
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
 
- name: Install epel on centos
  yum: name=epel-release state=latest
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

- name: Install nginx webserver on centos
  yum: name=nginx state=latest
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
